-- 코드를 입력하세요
SELECT MCDP_CD "진료과 코드", COUNT(MCDP_CD) "5월예약건수"
FROM APPOINTMENT 
WHERE APNT_YMD BETWEEN TO_DATE('2022-05-01', 'YYYY-MM-DD') AND
    TO_DATE('2022-06-01', 'YYYY-MM-DD')
GROUP BY MCDP_CD
ORDER BY "5월예약건수" ASC, MCDP_CD ASC;