-- 코드를 입력하세요
SELECT  BOOK_ID,AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD')PUBLISHED_DATE
FROM BOOK b RIGHT JOIN AUTHOR  a ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE CATEGORY IN ('경제')
ORDER BY PUBLISHED_DATE;
